# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

highlighter: pygments
paginate: 20 # pagination based on number of posts
paginate_path: "page/:num"

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
categories_path : categories.html
tags_path : tags.html

BASE_PATH : http://jitlee.github.io/blog

title : Jitlee-Wan



author:
    name: Jitlee.Wan
    role: 如果你简单，这个世界就对你简单
    email: www.wpj@163.com
    github: jitlee
    twitter: jitlee
    qq: www.wpj@163.com
    weibo: jitlee
    facebook: jitlee
    googleplus: +Jitlee
    bio: "嗨，我是万佳，一名来自深圳的js/swift开发狗，现在就职与一家互联网创业公司。"
    jitlee: /jitlee.gif
